# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/lega-vps.mooo.com
cert = /etc/letsencrypt/live/lega-vps.mooo.com/cert.pem
privkey = /etc/letsencrypt/live/lega-vps.mooo.com/privkey.pem
chain = /etc/letsencrypt/live/lega-vps.mooo.com/chain.pem
fullchain = /etc/letsencrypt/live/lega-vps.mooo.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d57dd909849aeb34aee9aeb0051a4f3a
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
